before:
  hooks:
    - go mod tidy
builds:
- id: "terraform-provider-basexform"
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  goarm:
    - 6
    - 7
  flags:
    - -trimpath
  ldflags:
    - -s -w
  env:
    - CGO_ENABLED=0
archives:
- id: "terraform-provider-basexform"
  builds:
    - "terraform-provider-basexform"
  format: tar.gz
  files:
    - none
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
signs:
  - artifacts: checksum
    args: ["--batch", "--yes", "--detach-sign", "--output", "${signature}", "${artifact}"]
